name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Debug
      
    - name: Build
      run: cmake --build build
      
    - name: Test
      run: |
        cd build
        ctest --verbose
